### ISSUE TITLE
Hangs on all functions

### ISSUE THREAD

**Issue by bluejorts** [fnuecke/lama#5]
All functions, including `lama.init()` hang when run. No error messages are thrown. Compatibility issue with new versions of CC maybe?

**Comment by fnuecke** [comment]
Yeah, that's quite likely. I haven't touched this code in over a year ;)

I'm busy keeping my own mod up-to-date and bug-free now, though, so I don't really have the time to figure out what changed and fix it. I'd happily accept a pull request fixing it!

**Comment by umnikos** [comment]
5 years later and there's still no fix :|

**Comment by bluejorts** [comment]
lol talk about a necrobump. Closing this.
